version: "3.9"

services:

  app:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - DATABASE_URI=${DATABASE_URI}
      - ENV=${ENV}

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    container_name: redis
    image: redis:6.2-alpine

  celery-worker:
    build: ./app
    command: celery -A celery_tasks worker --loglevel=info
    depends_on:
      - app
      - redis
    environment:
      - FROM_EMAIL=${FROM_EMAIL}
      - FROM_EMAIL_PASSWORD=${FROM_EMAIL_PASSWORD}
    volumes:
      - ./data/reports:/reports
  
  celery-beat:
    build: ./app
    command: celery -A celery_tasks beat --loglevel=info
    depends_on:
      - app
      - redis

volumes:
  postgres_data: